version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.docker/config.json:/config.json
    command: --interval 10 --label-enable

  maquette1:
    image: docker.pkg.github.com/julienkeiff/docker-registry/maquette1:latest
    hostname: maquette1
    restart: always
    environment:
      PORT: 3007
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    expose:
      - 3007
    ports:
      - 3007:3007